version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      electron-forge:
        patterns:
          - "@electron-forge/*"
          - electron
          - "@electron/*"
